name: verify

on:
  push:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: npm
      - uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: 145.0.7632.159
      - run: npm ci
      - run: npm run verify
